version: "3.7"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=company-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.rpc.address=:18861"
      - "--log.level=DEBUG"
      - "--serverstransport.insecureskipverify"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-http.entrypoints=web"
      - "traefik.http.routers.traefik-http.rule=Host(`traefik.company.com`)"
      - "traefik.http.routers.traefik-http.middlewares=traefik-https"
      - "traefik.http.middlewares.traefik-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.entrypoints=web-secure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.company.com`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.services.traefik.loadbalancer.server.scheme=http"
    ports:
      - "80:80"
      - "443:443"
      - "18861:18861"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/traefik/certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
      - $HOME/certs:/etc/certs/
    networks:
      - company-network

networks:
  company-network:
    external:
      name: company-network
